server:
  port: 9595
spring:
  kafka:
    bootstrap-servers: 22.239.16.12:9092,22.239.16.13:9092,22.239.16.14:9092,22.239.16.15:9092,22.239.16.16:9092,22.239.16.17:9092
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      order_inserts: true
      order_updates: true
      generate_statistics: true
      ddl-auto: update
      connection:
        autocommit: false
      jdbc:
        batch_size: 10000
        batch_versioned_data: true
  datasource:
    url: jdbc:mysql://22.239.129.50:3306/notes_db?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: notes
    password: Sp3ctrum
    hikari:
      idleTimeout: 10000
      minimumIdle: 5
      maximumPoolSize: 10
      connectionTimeout: 30000
      autoCommit: false
      poolName: NOTES_Hikari_Pool

app:
  topic:
    properties: properties.cmts
    snmpMetrics:
    #edgeData: dirty.cablemodem,dirty.interface,dirty.cmts,dirty.equipment,dirty.equipmentbackplane,dirty.equipmentchassis,dirty.equipmentfan,dirty.equipmentmodule,dirty.equipmentpowersupply
    edgeData:
  consumer:
    group-id: notes-test
    client-id: notes-test
    auto-offset-reset: earliest
    enable-auto-commit: true
    poll-timeout: 3000
    concurrency: 30
    max-partition-fetch-bytes: 3048576
    max-record-per-poll: 10000
  json:
    converter:
      ignoreUnknown: false
  #logging:
  #  level:
  #   root: ERROR
  #   org.springframework.web: ERROR
  #   com.memorynotfound: DEBUG