server:
  port: 9595
spring:
  kafka:
    bootstrap-servers: 22.239.144.4:9092,22.239.144.5:9092,22.239.144.6:9092,22.239.144.7:9092,22.239.144.8:9092,22.239.144.9:9092
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      order_inserts: true
      order_updates: true
      generate_statistics: true
      ddl-auto: update
      connection:
        autocommit: false
      jdbc:
        batch_size: 10000
        batch_versioned_data: true
  datasource:
    url: jdbc:mysql://22.239.129.50:3306/notes_db?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: notes
    password: Sp3ctrum
    hikari:
      idleTimeout: 10000
      minimumIdle: 5
      maximumPoolSize: 15
      connectionTimeout: 30000
      autoCommit: false
      poolName: NOTES_Hikari_Pool

app:
  topic:
    properties:
    snmpMetrics:
    edgeData: dirty.cablemodem,dirty.interface,dirty.cmts,dirty.equipment,dirty.equipmentbackplane,dirty.equipmentchassis,dirty.equipmentfan,dirty.equipmentmodule,dirty.equipmentpowersupply
  consumer:
    group-id: notes-dirty-data-consumer-test
    client-id: notes-dirty-data-consumer-test
    auto-offset-reset: latest
    enable-auto-commit: true
    poll-timeout: 4000
    concurrency: 36
    max-partition-fetch-bytes: 7048576
    max-record-per-poll: 10000
  json:
    converter:
      ignoreUnknown: false
#logging:
#  level:
 #   root: ERROR
 #   org.springframework.web: ERROR
 #   com.memorynotfound: DEBUG