apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "14"
    field.cattle.io/creatorId: user-wrs7d
    field.cattle.io/publicEndpoints: '[{"addresses":["22.239.1.22"],"port":31974,"protocol":"TCP","serviceName":"kafka-consumers:noc-edge-consumer-nodeport","allNodes":true},{"nodeName":"c-lz7qx:m-e522a13e5e8b","addresses":["22.239.1.26"],"port":9595,"protocol":"TCP","podName":"kafka-consumers:noc-edge-consumer-786bf99cf4-w5h9l","allNodes":false}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-kafka-consumers-noc-edge-consumer
  name: noc-edge-consumer
  selfLink: /apis/apps/v1beta2/namespaces/kafka-consumers/deployments/noc-edge-consumer
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-kafka-consumers-noc-edge-consumer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2019-02-12T18:56:44Z
        field.cattle.io/ports: '[[{"containerPort":9595,"dnsName":"noc-edge-consumer-nodeport","kind":"NodePort","name":"9595tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-kafka-consumers-noc-edge-consumer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: noc-consumer
                operator: In
                values:
                - "true"
      containers:
      - env:
        - name: LOGGING_CONFIG
          value: /config/logback.xml
        - name: SPRING_CONFIG_LOCATION
          value: /appConfig/application.yml
        image: 98.8.61.7:5000/notes-data-consumer:0.1.6
        imagePullPolicy: Always
        name: noc-edge-consumer
        ports:
        - containerPort: 9595
          hostPort: 9595
          name: 9595tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: logback-config
        - mountPath: /appConfig
          name: application-config
        - mountPath: /var/log/notes/noc
          name: log-dir
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          name: noc-edge-consumer-logback
          optional: false
        name: logback-config
      - configMap:
          defaultMode: 256
          name: noc-edge-consumer-app-config
          optional: false
        name: application-config
      - hostPath:
          path: /var/log/notes/noc
          type: ""
        name: log-dir
status: {}
